# Generated by Django 3.1 on 2021-11-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('family_name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
